platform :ios, '9.0'

target 'FMComponentKitExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'FMComponentKit', :path => './../'

end
